### PR TITLE
Information missing from PDF version #23

### PR DESCRIPTION
**Pull request by ChouaibB**
* pdf download functionality added at the top of the html pages
* Whole material rendered as a pdf book with some formatting
* Tables printing has been changed (temporarily) for tables not breaking at the pdf book.

### CODE REVIEW

**Comment by TuomasBorman** [comment]
Thanks! 

Now it works, however, I am not completely sure about the format of the table. So we could discuss about that

I tried to solve this also, and I found that we could keep this style that we had before, and scale tables in pdf version by adding one argument. 

I think this should work:

```
knitr::kable(head(rowData(tse))) %>% 
  kableExtra::kable_styling("striped", latex_options="scale_down") %>% 
  kableExtra::scroll_box(width = "100%")
```
 
So, just `latex_options = "scale_down"` is added. The downside is that then longer tables are smaller. 

I think also that we need to add 

install.packages("webshot")
webshot::install_phantomjs()

because they are needed to create pdf formatted stuff from html (https://bookdown.org/yihui/bookdown/html-widgets.html)

**Comment by ChouaibB** [comment]
Okay, I have been trying to look for a way to keep the same table formats, however with the slider they broke during pdf rendering.
I'll try that option, thanks.

**Comment by TuomasBorman** [comment]
I made another implementation that utilize `knitr::kable()`. However, it also has some downsides

PR : https://github.com/microbiome/course_2021_radboud/pull/32

**Comment by antagomir** [comment]
This is out of sync - still topical?

**Pull request closed without merging**
